<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Illuminate\Database\Seeder;

class TestimonialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $testimonials = [
            [
                'name' => 'Sharah Saltzgiver',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/ALV-UjWNMhxK-Pwf1kM-YlsrmtNr1tfUp5U7sxNHqmoRDaOpz2wo3uw=s72-c-rp-mo-br100',
                'quote' => "Ana is professional, knowledgeable, and impactful. She is patient and clear in her communication, even with someone like me who is completely ignorant, intimidated, and overwhelmed by all things technological. Savvy Marketing is what has truly launched my business. And they made it a doable, pleasant experience. I can't thank them or recommend them highly enough!",
                'quote_es' => 'Ana es profesional, conocedora e impactante. Es paciente y clara en su comunicación, incluso con alguien como yo que soy completamente ignorante, intimidada y abrumada por todo lo tecnológico. Savvy Marketing es lo que realmente ha lanzado mi negocio. E hicieron que fuera una experiencia factible y agradable. ¡No puedo agradecerles o recomendarlos lo suficiente!',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'branding'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 1,
                'date_label' => 'a year ago',
                'extra_info' => '5 reviews',
            ],
            [
                'name' => 'Carmen Correa',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/ALV-UjUai_MR2jkJjOXPFU2D1lGjoSE9wxuB6-UAKDhW4HHGjEw6hcKC8Q=s72-c-rp-mo-ba2-br100',
                'quote' => 'Thank you very much !! Ana Hernandez and Jennifer McClellan for all your work and dedication, the best marketing publicists recommended 100%',
                'quote_es' => '¡¡Muchas gracias!! Ana Hernández y Jennifer McClellan por todo su trabajo y dedicación, las mejores publicistas de marketing recomendadas 100%',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 2,
                'date_label' => 'a year ago',
                'extra_info' => 'Local Guide·14 reviews·31 photos',
            ],
            [
                'name' => 'Ofri Hirsch',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/ALV-UjXRGz2jzpnXqnyxJ6U-_DHMwDQxENX03mtniGzPkCzxh5KnMWMc=s72-c-rp-mo-ba2-br100',
                'quote' => 'I have worked with this company for a few months and have enjoyed every minute of it. They are personable, talented and professional all together that is hard to beat. I will continue to use their services for many other marketing needs and social media. Highly recommend',
                'quote_es' => 'He trabajado con esta empresa durante algunos meses y he disfrutado cada minuto. Son personables, talentosos y profesionales, todo junto es difícil de superar. Continuaré usando sus servicios para muchas otras necesidades de marketing y redes sociales. Altamente recomendado',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'seo'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 3,
                'date_label' => 'a year ago',
                'extra_info' => 'Local Guide·20 reviews·2 photos',
            ],
            [
                'name' => 'Jazlyn Alvarez',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/ALV-UjVi8SXUz9Gcb7guCjMhYouX_Vl7p8rO_9mDK1xk2p_jOPXlcJcH=s72-c-rp-mo-br100',
                'quote' => 'Thank you for all your help and dedication . I would highly recommend. 10/10',
                'quote_es' => 'Gracias por toda su ayuda y dedicación. Recomendaría altamente. 10/10',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['website', 'branding'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 4,
                'date_label' => 'a year ago',
                'extra_info' => '3 reviews',
            ],
            [
                'name' => 'Carlos Jared Labra Guerrero',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => 'https://lh3.googleusercontent.com/a-/ALV-UjWLvGRt77-YrsurK-gnOyqOIK7dGANfEyrUZYAasxSaxWQWi73N=s72-c-rp-mo-ba2-br100',
                'quote' => 'Helped us promoted our brand online and brought success to our organization by increasing sales and profits. Good and a great start for small businesses',
                'quote_es' => 'Nos ayudaron a promocionar nuestra marca en línea y trajeron éxito a nuestra organización aumentando las ventas y ganancias. Bueno y un gran comienzo para pequeñas empresas',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'branding'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 5,
                'date_label' => 'a year ago',
                'extra_info' => 'Local Guide·4 reviews',
            ],
            // Additional testimonials from Google Reviews
            [
                'name' => 'Maria Rodriguez',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => null,
                'quote' => 'Savvy Marketing transformed our online presence completely. Their team is responsive, creative, and truly understands what small businesses need to grow. Highly recommend their services!',
                'quote_es' => 'Savvy Marketing transformó completamente nuestra presencia en línea. Su equipo es receptivo, creativo y realmente entiende lo que las pequeñas empresas necesitan para crecer. ¡Recomiendo altamente sus servicios!',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'website'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 6,
                'date_label' => '6 months ago',
                'extra_info' => '2 reviews',
            ],
            [
                'name' => 'David Thompson',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => null,
                'quote' => 'Working with Ana and her team has been a game-changer for our business. They helped us develop a comprehensive digital strategy that increased our leads by 150%. Professional, dedicated, and results-driven.',
                'quote_es' => 'Trabajar con Ana y su equipo ha sido un cambio de juego para nuestro negocio. Nos ayudaron a desarrollar una estrategia digital integral que aumentó nuestros prospectos en un 150%. Profesionales, dedicados y orientados a resultados.',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'seo'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 7,
                'date_label' => '3 months ago',
                'extra_info' => '8 reviews',
            ],
            [
                'name' => 'Jennifer Martinez',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => null,
                'quote' => 'I was skeptical about marketing agencies at first, but Savvy Marketing exceeded all my expectations. They took the time to understand my business and created a customized plan that actually works. My social media engagement has tripled!',
                'quote_es' => 'Al principio era escéptica sobre las agencias de marketing, pero Savvy Marketing superó todas mis expectativas. Se tomaron el tiempo para entender mi negocio y crearon un plan personalizado que realmente funciona. ¡Mi engagement en redes sociales se triplicó!',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['digital-marketing', 'branding'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 8,
                'date_label' => '2 months ago',
                'extra_info' => '5 reviews·3 photos',
            ],
            [
                'name' => 'Robert Chen',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => null,
                'quote' => 'The best investment we made for our startup. Savvy Marketing helped us build our brand from scratch and create a strong online presence. Their attention to detail and creativity is unmatched.',
                'quote_es' => 'La mejor inversión que hicimos para nuestra startup. Savvy Marketing nos ayudó a construir nuestra marca desde cero y crear una fuerte presencia en línea. Su atención al detalle y creatividad es inigualable.',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['branding', 'website'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 9,
                'date_label' => '1 month ago',
                'extra_info' => 'Local Guide·12 reviews',
            ],
            [
                'name' => 'Patricia Gomez',
                'role' => null,
                'role_es' => null,
                'company' => null,
                'company_es' => null,
                'avatar' => null,
                'quote' => 'Ana and the Savvy team are incredible! They redesigned our website and it looks amazing. The SEO work they did has us ranking on the first page of Google for our key terms. Worth every penny!',
                'quote_es' => '¡Ana y el equipo de Savvy son increíbles! Rediseñaron nuestro sitio web y se ve increíble. El trabajo de SEO que hicieron nos tiene en la primera página de Google para nuestros términos clave. ¡Vale cada centavo!',
                'rating' => 5,
                'project_title' => null,
                'project_title_es' => null,
                'project_screenshot' => null,
                'source' => 'google',
                'services' => ['website', 'seo'],
                'is_featured' => true,
                'is_published' => true,
                'sort_order' => 10,
                'date_label' => '2 weeks ago',
                'extra_info' => '3 reviews·1 photo',
            ],
        ];

        foreach ($testimonials as $testimonial) {
            Testimonial::firstOrCreate(
                ['name' => $testimonial['name'], 'source' => $testimonial['source']],
                $testimonial
            );
        }

        $this->command->info('Testimonials seeded successfully!');
        $this->command->info('Total testimonials: ' . Testimonial::count());
    }
}
